include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/*.gr.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Best practices
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_unnecessary_containers: true
    use_super_parameters: true
    unawaited_futures: true
    cancel_subscriptions: true

    # Style & consistency
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    lines_longer_than_80_chars: false

    # Safety
    avoid_type_to_string: true
    avoid_positional_boolean_parameters: true
    unnecessary_null_checks: true

    # Optional stricter rules
    avoid_classes_with_only_static_members: true
    avoid_field_initializers_in_const_classes: true
    constant_identifier_names: false # set to true if you want to enforce SCREAMING_SNAKE_CASE
