// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstJ8wUUa5Nb5-UmsAqo5fTtbUPmW8uWM',
    appId: '1:152856451676:web:07fd561d3d8d05c1eae499',
    messagingSenderId: '152856451676',
    projectId: 'edutainstem',
    authDomain: 'edutainstem.firebaseapp.com',
    storageBucket: 'edutainstem.firebasestorage.app',
    measurementId: 'G-0CW5DN8ZDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-VrSye2l5nFemm6GhPPW9_UX1CCnSZjg',
    appId: '1:152856451676:android:746d9be02164c2f4eae499',
    messagingSenderId: '152856451676',
    projectId: 'edutainstem',
    storageBucket: 'edutainstem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvKLUfnHitF8FgL7kqpL_UzPVFVBCz268',
    appId: '1:152856451676:ios:03985a898e81edd5eae499',
    messagingSenderId: '152856451676',
    projectId: 'edutainstem',
    storageBucket: 'edutainstem.firebasestorage.app',
    iosBundleId: 'com.example.edutainstem',
  );
}